### ISSUE TITLE
HTML editing for cells?

### ISSUE THREAD

**Issue by mattrice** [Mesuva/msv_table#2]
Would it be possible to get HTML into a cell? It does not even have to be anything fancy like the WYSIWYG editor.

Any ideas on how that could be accomplished?

**Comment by Mesuva** [comment]
The challenge with HTML in cell isn't so much the output, it's working out how this would be handled by the handsontable. The handsontable grid can be configured to output HTML content with a renderer, but it's not (as far as I've seen) got a nice way to enter such content.

Ultimately the purpose of the block is to output tabular data, not do act as a way to build HTML tables. My thinking is that if someone wants to do more complex formatting, they should use a WYSIWYG editor. I know Redactor isn't very good for this in 5.7, but I have packaged up CKEditor (https://github.com/Mesuva/ckeditor_content) as an example of a different editor.

If you can see an easy way to add HTML functionality, without breaking the way existing data is stored I'd be keen to hear it!

**Comment by Mesuva** [comment]
This issue is from ages ago, but I just wanted to note that the recent version of this does include Markdown support, so you can get some basic formatting in place. It's not pure HTML, but it allows links and other simple formatting to happen.
