### ISSUE TITLE
support for handsontable properties

### ISSUE THREAD

**Issue by Remo** [Mesuva/msv_table#3]
I really like the inline editing interface, but I wonder who we could support initialization properties like `rowHeaders` and `colHeaders`. We've been using them in our 5.6 block in the past.

Any ideas on how to approach this? We could contribute some code for this..

**Comment by Remo** [comment]
I wasn't aware of it, but it seems like we can add custom context menu entries: http://docs.handsontable.com/0.15.0-beta6/demo-context-menu.html#page-custom

Would you merge a PR that adds a menu where we can set some properties like `rowHeaders`?

**Comment by Mesuva** [comment]
If you think you can come up with a nice way to enable/disable the headers, I'd certainly welcome it.

I've actually done some work on this block recently, will push that up to github shortly so you have the latest version.
