### ISSUE TITLE
cell styling using CSS classes

### ISSUE THREAD

**Issue by Remo** [Mesuva/msv_table#4]
We used to have a feature with which we could assign CSS classes to cells. No formatting in the cells, simply a class like `bold` or `highlighted` which we could assign to cells.

What if we'd create an array in `page_theme.php` where one could specify some CSS classes which would then be listed as a menu-item with sub-items in the context menu?

**Comment by Mesuva** [comment]
I did think about adding this feature, but I held off as I thought of other things that might be wanted such as links - so I recently added Markdown support (I discovered a Markdown class is already included with 5.7).  Just pushed that up.

It's no-where near as as elegant as having formatting options in the contextual menu, but it then means you've got a whole lot more that you can do.

What you've described sounds pretty handy though, especially to bold things.

**Comment by Remo** [comment]
This looks pretty cool, not so much user friendly for those of us who don't like things like markdown, but definitely powerful. I wonder what will happen if we'd select the markdown template and also select a "bold" style..

Maybe I have some time or have someone who has some time to look into this.

**Comment by Remo** [comment]
This is what our old block looks like:

![image](https://cloud.githubusercontent.com/assets/129864/9899629/55bac1ee-5c5b-11e5-9546-d430b0ae092f.png)
