### ISSUE TITLE
Showing as corrupt package in 5.7.5.9

### ISSUE THREAD

**Issue by Bolad32** [Mesuva/msv_table#9]
Hi there, I've been struggling to style a table for a client site and this was about to save my bacon! However, when uploaded to the packages folder it will not install, saying that the Add-On is corrupt.
I would really like to use this if there is any chance it might be updated to work on this version or above??

**Comment by mhawke** [comment]
Have you renamed the "/packages/msv_table_master" folder to just "/packages/msv_table"?

**Comment by Mesuva** [comment]
Yes, that was the problem @mhawke
